/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sketchbook.gltf --transform
Author: Seishi (https://sketchfab.com/Seishi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sketchbook-5182049f5e6e48c89282287c0c9bf13e
Title: Sketchbook
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sketchbook-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.01]} rotation={[0, 0.09, 0]}>
        <mesh geometry={nodes.pCylinder1_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.pCylinder1_blinn2_0.geometry} material={materials.blinn2} />
        <mesh geometry={nodes.pCylinder1_lambert5_0.geometry} material={materials.lambert5} />
      </group>
      <group position={[-0.24, 0, -0.35]} rotation={[0, 0.02, 0]}>
        <mesh geometry={nodes.pCylinder2_lambert5_0.geometry} material={materials.lambert5} />
        <mesh geometry={nodes.pCylinder2_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.pCylinder2_blinn2_0.geometry} material={materials.blinn2} />
      </group>
      <group position={[0, -0.02, 0]} rotation={[0, 0, 0.01]}>
        <mesh geometry={nodes.pCylinder3_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.pCylinder3_blinn2_0.geometry} material={materials.blinn2} />
        <mesh geometry={nodes.pCylinder3_lambert5_0.geometry} material={materials.lambert5} />
      </group>
      <group position={[0.39, 0, 0.88]} rotation={[0, -0.14, 0]}>
        <mesh geometry={nodes.pCylinder4_lambert5_0.geometry} material={materials.lambert5} />
        <mesh geometry={nodes.pCylinder4_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.pCylinder4_blinn2_0.geometry} material={materials.blinn2} />
      </group>
      <mesh geometry={nodes.pCube1_lambert3_0.geometry} material={materials.lambert3} position={[0, 0.13, 0]} scale={[6.07, 0.22, 3.9]} />
      <mesh geometry={nodes.pCube3_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCube4_phong1_0.geometry} material={materials.phong1} position={[0, 0.32, 0]} scale={[1, 0.28, 1]} />
      <mesh geometry={nodes.pCube5_lambert4_0.geometry} material={materials.lambert4} position={[0, -0.03, 0]} scale={[1, 0.28, 1]} />
      <mesh geometry={nodes.pTorus3_phong2_0.geometry} material={materials.phong2} />
      <mesh geometry={nodes.pTorus4_phong2_0.geometry} material={materials.phong2} position={[0, 0, 0.37]} />
      <mesh geometry={nodes.pTorus5_phong2_0.geometry} material={materials.phong2} position={[0, 0, 0.73]} />
      <mesh geometry={nodes.pTorus6_phong2_0.geometry} material={materials.phong2} position={[0, 0, 1.1]} />
      <mesh geometry={nodes.pTorus7_phong2_0.geometry} material={materials.phong2} position={[0, 0.06, 1.47]} rotation={[-0.03, 0, 0]} />
      <mesh geometry={nodes.pTorus8_phong2_0.geometry} material={materials.phong2} position={[0, 0.07, 1.84]} rotation={[-0.03, 0, 0]} />
      <mesh geometry={nodes.pTorus9_phong2_0.geometry} material={materials.phong2} position={[0, 0.12, 2.21]} rotation={[-0.05, 0, 0]} />
      <mesh geometry={nodes.pTorus10_phong2_0.geometry} material={materials.phong2} position={[0, 0.14, 2.57]} rotation={[-0.05, 0, 0]} />
      <mesh geometry={nodes.pTorus11_phong2_0.geometry} material={materials.phong2} position={[0, 0.07, 2.93]} />
      <mesh geometry={nodes.pTorus12_phong2_0.geometry} material={materials.phong2} position={[0, 0.07, 3.3]} />
      <mesh geometry={nodes.pCube6_lambert2_0.geometry} material={materials.lambert2} position={[-1.82, 0.51, 1.29]} rotation={[-0.06, -0.96, -0.07]} scale={[0.95, 0.24, 0.68]} />
    </group>
  )
}

useGLTF.preload('/sketchbook-transformed.glb')
